name: Create Release Tag

on:
  repository_dispatch:
    types: [create-release-event]
    inputs:
      version:
        description: 'Enter the version number for the release (e.g., 0.0.1)'
        required: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release Tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
