name: Create Release Tag

on:
  repository_dispatch:
    types: [create-release-event]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release Tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.version }}
        release_name: Release ${{ github.event.client_payload.version }}
        draft: false
        prerelease: false
