name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number (e.g., 0.0.1)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Create Release Branch
      run: |
        git config --global user.name 'harsha'
        git config --global user.email 'vishnuvardhan7965@gmail.com'
        git checkout -b release/v${{ github.event.inputs.version }}
        git push origin release/v${{ github.event.inputs.version }}
    
    - name: Trigger Release Creation Workflow
      uses: actions/github-script@0.9.0
      with:
        script: |
          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'create-release-event',
            client_payload: {
              version: '${{ github.event.inputs.version }}'
              }
            })
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
