name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number (e.g., 0.0.1)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop
        token: ${{ secrets.PAT }}

    - name: Create Release Branch
      run: |
        git config --global user.name 'harsha'
        git config --global user.email 'vishnuvardhan7965@gmail.com'
        git checkout -b release/v${{ github.event.inputs.version }}
        git push origin release/v${{ github.event.inputs.version }}
    
    - name: Create Release Tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT}}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
    
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.PAT }}
        destination_branch: "main"
        source_branch: "release/v${{ github.event.inputs.version }}"
        pr_title: "Merge release v${{ github.event.inputs.version }} into main"
        pr_body: "This PR was auto-generated by a GitHub Action to merge the release branch into the main branch."
        # pr_reviewer: <username1>,<username2> # Optional: Add reviewers
        # pr_assignee: <username> # Optional: Assign someone
        pr_label: "release, auto-pr" # Optional: Add labels