name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number (e.g., 0.0.1)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release Branch
      run: |
        git checkout -b release/v:${{ github.event.inputs.version }}
        git push origin release/v:${{ github.event.inputs.version }}
